name: Backend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

      # Migrate database
    - name: Run database migrations
      env:
        DJANGO_SETTINGS_MODULE: 'backend.settings' # Replace with your settings module
      run: |
        python manage.py migrate