name: Backend/Frontend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Save the SSH private key to a file
        echo "${SSH_KEY}" > ec2-key.pem
        chmod 600 ec2-key.pem  # Set permissions for the SSH key file

    - name: Connect to EC2 Instance via SSH
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # SSH into EC2 instance and run a simple command
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${EC2_USER}@${EC2_HOST} "uptime"

          # Navigate to the home directory
          cd /home/

          # Activate the virtual environment
          source ubuntu/env/bin/activate

          #Navigate to the project dir
          cd ubuntu/projects_management
          pip install -r requirements.txt