name: Backend/Frontend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to EC2
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "${SSH_KEY}" > ec2-key.pem
        chmod 600 ec2-key.pem
      
        # SSH into EC2 and perform operations
        ssh -i ec2-key.pem ubuntu@${EC2_HOST} << 'EOF'
        cd /home/ubuntu/projects_management

        # Pull latest code from GitHub
        git pull origin main

        # Activate virtual environment and install dependencies
        source env/bin/activate
        pip install -r requirements.txt

        # Apply Django migrations
        cd /home/ubuntu/projects_management/backend
        python manage.py migrate

         #Apply react changes
        cd /home/ubuntu/projects_management/frontend
        npm install
        npm run build

        # Restart services
        sudo systemctl restart gunicorn
        sudo systemctl restart nginx