name: Backend/Frontend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        # Save the SSH private key to a file
        echo "${SSH_KEY}" > ec2-key.pem
        chmod 600 ec2-key.pem  # Set permissions for the SSH key file

    - name: Connect to EC2 Instance via SSH
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        # SSH into EC2 instance and run commands in one SSH session
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${EC2_USER}@${EC2_HOST} <<EOF
          # Show the uptime of the server
          uptime

          # List the contents of /home/
          echo "Listing contents of /home/"
          ls -l /home/

          # List the contents of /home/ubuntu/
          echo "Listing contents of /home/ubuntu/"
          ls -l /home/ubuntu
          source /home/ubuntu/env/bin/activate
          
        EOF
